# Generated by Django 4.0.7 on 2023-02-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'practice',
            },
        ),
    ]
